platform: linux

image_resource:
  type: docker-image
  source:
    repository: aucnet4dev/springboot
    tag: latest

inputs:
  - name: source
outputs:
  - name: package
run:
  path: "source/ci/scripts/package.sh"